version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup Virtual Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
            python -m venv .venv
            . .venv/bin/activate
            pip install --no-cache-dir -r app/requirements.txt
      - run:
          name: Run Tests
          command: |
            . .venv/bin/activate
            python app/test_hello_world.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . .venv/bin/activate
            pyinstaller -F app/hello_world.py
            docker build -t ariv3ra/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ariv3ra/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"